<a href="https://colab.research.google.com/github/Sangeetha16092006/Data-Analytics-using-Python-Project/blob/main/Error_Handling__Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  num=int(input("Enter Number:"))
  print(num)
except:
  print("Invalid Input")

Enter Number:2
2


In [ ]:
def calculate_average(a,b,c):
  return(a+b+c)/3

try:
  a=int(input("Enter 1st number:"))
  b=int(input("Enter 2nd number:"))
  c=int(input("Enter 3rd number:"))
  print("calculate_average=",calculate_average(a,b,c))
except ValueError:
  print("Invalid Input")

Enter 1st number:80
Enter 2nd number:90
Enter 3rd number:70
calculate_average= 80.0


In [ ]:
def attendance_percentage(attended,total):
  percentage=attended/total*100
  return round(percentage,2)

def check_eligibility(percent):
  if percent>=75:
    return "ELIGIBLE"
  else:
    return "NOT ELIGIBLE"

try:
  total=int(input("Total Classes:"))
  attended=int(input("Classes Attended:"))
  pct=attendance_percentage(attended,total)
  status=check_eligibility(pct)

  print(f"Attendance:{pct}%")
  print(f"status:{status}")

except valueError:
  print("Error:Enter valid numbers")


Total Classes:100
Classes Attended:80
Attendance:80.0%
status:ELIGIBLE


In [ ]:
import numpy as np

marks=np.array([90,85,78,92])

print(marks)

[90 85 78 92]


In [ ]:
import numpy as np

students=np.array([
    [90,85],
    [78,92],
    [88,95]
])
print(students)

[[90 85]
 [78 92]
 [88 95]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a+b)
#[11 22 33 44]

print(a*b)
#[10 40 90 160]

print(np.sqrt(a))
#[1.  1.41  1.73  2.]

print(np.sum(a))
#10

print(np.mean(b))
#25.0


[11 22 33 44]
[ 10  40  90 160]
[1.         1.41421356 1.73205081 2.        ]
10
25.0
