<a href="https://colab.research.google.com/github/Sangeetha16092006/Data-Analytics-using-Python-Project/blob/main/Indexing_and_slicing_DAY_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([90,85,78,92])
print(marks[2])

78


In [ ]:
import numpy as np
marks=np.array([90,85,78,92])
print(marks[1:4])

[85 78 92]


In [ ]:
scores=[78,85,92,67,88]

total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)

print("Student Scores:",scores)
print("Total Marks:",total)
print("Average Marks",average)
print("Highest Marks",highest)
print("Lowest Marks",lowest)

Student Scores: [78, 85, 92, 67, 88]
Total Marks: 410
Average Marks 82.0
Highest Marks 92
Lowest Marks 67


In [ ]:
sales=[12000,15000,18000.14000,20000]

total_sales=sum(sales)
average_sales=total_sales/len(sales)
highest_sales=max(sales)
lowest_sales=min(sales)

print("Monthly Sales:",sales)
print("Total Sales:",total_sales)
print("Average Sales:",average_sales)
print("Highest Sales:",highest_sales)
print("Lowest Sales:",lowest_sales)

Monthly Sales: [12000, 15000, 18000.14, 20000]
Total Sales: 65000.14
Average Sales: 16250.035
Highest Sales: 20000
Lowest Sales: 12000


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
marks=np.array([70,80,90,68])
average=np.mean(marks)
print(average)

77.0


In [ ]:
import numpy as np
salary=np.array([10000,20000,30000,40000,50000])
med=np.median(salary)
print(med)

30000.0
